### ISSUE TITLE
10.15.4 recipe robot fails

### ISSUE THREAD

**Issue by albiii** [homebysix/recipe-robot#161] opened 2020-05-03 03:19 UTC
Autopkg 2.0.2
xcode Git
 /usr/local/bin/recipe-robot --verbose
Traceback (most recent call last):
  File "/usr/local/bin/recipe-robot", line 42, in <module>
    import recipe_robot_lib
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/__init__.py", line 26, in <module>
    from .recipe_generator import generate_recipes
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/recipe_generator.py", line 34, in <module>
    from . import processor
  File "/Applications/Recipe Robot.app/Contents/Resources/scripts/recipe_robot_lib/processor.py", line 38, in <module>
    import autopkglib
  File "/Library/AutoPkg/autopkglib/__init__.py", line 185
    raise PreferenceError(f"Could not synchronize preference {key}")
                                                                  ^

**Comment by albiii** [comment] 2020-05-03 03:19
I have not tried recipe robot on 10.14.6

**Comment by homebysix** [comment] 2020-05-03 03:56
Duplicate of https://github.com/homebysix/recipe-robot/issues/156.

**Closed by homebysix** 2020-05-03 03:56 UTC
